### ISSUE TITLE
something wrong when "python setup.py build_ext --inplace"

### ISSUE THREAD

**Issue by caixxuan** [CAS-LRJ/ISS#20]
building 'ISS.algorithms.utils.postprocessingutils.iou3d.iou3d_nms_cuda' extension
Traceback (most recent call last):
  File "setup.py", line 62, in <module>
    setup(
  File "/home/cai/anaconda3/envs/iss/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "/home/cai/anaconda3/envs/iss/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/cai/anaconda3/envs/iss/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/cai/anaconda3/envs/iss/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/cai/anaconda3/envs/iss/lib/python3.8/site-packages/setuptools/dist.py", line 963, in run_command
    super().run_command(command)
  File "/home/cai/anaconda3/envs/iss/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/cai/anaconda3/envs/iss/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 88, in run
    _build_ext.run(self)
  File "/home/cai/anaconda3/envs/iss/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/cai/anaconda3/envs/iss/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/home/cai/anaconda3/envs/iss/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 709, in build_extensions
    build_ext.build_extensions(self)
  File "/home/cai/anaconda3/envs/iss/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/cai/anaconda3/envs/iss/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/home/cai/anaconda3/envs/iss/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/cai/anaconda3/envs/iss/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 249, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/cai/anaconda3/envs/iss/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
    objects = self.compiler.compile(
  File "/home/cai/anaconda3/envs/iss/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 525, in unix_wrap_ninja_compile
    cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
  File "/home/cai/anaconda3/envs/iss/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 424, in unix_cuda_flags
    cflags + _get_cuda_arch_flags(cflags))
  File "/home/cai/anaconda3/envs/iss/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1562, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range

**Comment by CAS-LRJ** [comment]
Sorry for the late reply, we are currently refactoring our code :)
The error here is mainly caused by CUDA. You may need to check if cuda is installed successfully.
We are going to convert our deep-learning models with tensorrt later, so current CUDA extension compile may be deprecated.
