### ISSUE TITLE
TypeError: 'Boost.Python.class' object is not iterable

### ISSUE THREAD

**Issue by shiliashili** [CAS-LRJ/ISS#25]
Traceback (most recent call last):
  File "run_carla.py", line 10, in <module>
    from ISS.algorithms.sensors.carla_actor_tree import CarlaActorTree
  File "ISS/algorithms/sensors/carla_actor_tree.pyx", line 5, in init ISS.algorithms.sensors.carla_actor_tree
    from ISS.algorithms.sensors.carla_actor_factory import CarlaActorFactory, CarlaNode
  File "ISS/algorithms/sensors/carla_actor_factory.pyx", line 12, in init ISS.algorithms.sensors.carla_actor_factory
    from ISS.algorithms.utils.sensorutils.transform import transform_to_carla_transform
  File "ISS/algorithms/utils/sensorutils/transform.pyx", line 172, in init ISS.algorithms.utils.sensorutils.transform
    def vertices_to_carla_bbox(vertices: list(carla.Location)):
TypeError: 'Boost.Python.class' object is not iterable

ubuntu22.04

**Comment by shiliashili** [comment]
This line was causing a TypeError because carla.Location is not iterable, and thus cannot be used with list.

To resolve this issue, I changed the line to:
`def vertices_to_carla_bbox(vertices: dir(carla.Location)):`
Then run the command:
`python setup.py build_ext --inplace`
to rebuild the Cython extensions.
